// flow-typed signature: f1cc6198d6a9af42347329635ebc2b03
// flow-typed version: <<STUB>>/swapi-node_v^0.4.4/flow_v0.89.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'swapi-node'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'swapi-node' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'swapi-node/example' {
  declare module.exports: any;
}

declare module 'swapi-node/lib/swapi-node' {
  declare module.exports: any;
}

declare module 'swapi-node/lib/util' {
  declare module.exports: any;
}

declare module 'swapi-node/test/swapi-api-tests' {
  declare module.exports: any;
}

declare module 'swapi-node/test/swapi-paging-test' {
  declare module.exports: any;
}

declare module 'swapi-node/test/swapi-subresources-test' {
  declare module.exports: any;
}

// Filename aliases
declare module 'swapi-node/example.js' {
  declare module.exports: $Exports<'swapi-node/example'>;
}
declare module 'swapi-node/index' {
  declare module.exports: $Exports<'swapi-node'>;
}
declare module 'swapi-node/index.js' {
  declare module.exports: $Exports<'swapi-node'>;
}
declare module 'swapi-node/lib/swapi-node.js' {
  declare module.exports: $Exports<'swapi-node/lib/swapi-node'>;
}
declare module 'swapi-node/lib/util.js' {
  declare module.exports: $Exports<'swapi-node/lib/util'>;
}
declare module 'swapi-node/test/swapi-api-tests.js' {
  declare module.exports: $Exports<'swapi-node/test/swapi-api-tests'>;
}
declare module 'swapi-node/test/swapi-paging-test.js' {
  declare module.exports: $Exports<'swapi-node/test/swapi-paging-test'>;
}
declare module 'swapi-node/test/swapi-subresources-test.js' {
  declare module.exports: $Exports<'swapi-node/test/swapi-subresources-test'>;
}
